"""empty message

Revision ID: 1e2ad29183ed
Revises: None
Create Date: 2016-02-20 12:36:39.855451

"""

# revision identifiers, used by Alembic.
revision = '1e2ad29183ed'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('year', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'year')
    ### end Alembic commands ###
